[platformio]
default_envs = tx, rx

[env]
platform = espressif32@6.10.0
platform_packages =
    framework-espidf@3.50400.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 921600
build_flags = -I include

[env:tx]
build_flags = ${env.build_flags} -DSRASTA_ROLE_TX=1

[env:rx]
build_flags = ${env.build_flags} -DSRASTA_ROLE_TX=0

[env:rx_hotspot]
build_flags = ${env.build_flags} -DSRASTA_ROLE_TX=0 -DSRASTA_HOTSPOT=1
